version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laraveldb
    volumes:
      - db-data:/var/lib/mysql:cached

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ../:/app:cached
    depends_on:
      - workspace #must be the same name of the laravel container used above

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db-data:

